branch-defaults:
  default:
    environment: irrigationPlannerEnv
    group_suffix: null
  main:
    environment: irrigationEnv3
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
  portalooTrackerEnv:
    branch: null
    repository: null
global:
  application_name: irrigationPlanner3
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
